export const proj = [
  {
    title: "Ecompilot Theme",
    titlesub: "Ecompilot Theme development",
    img: "",
    details: [
      "Custom Theme development",
      "Theme settings menu on theme activation",
      "Admin side interface",
      "Custom required plugin install",
      "Quick site installations",
      "Pre-made layout and sections",
    ],
    type: ["Wordpress Theme"],
    tech: ["Wordpress", "Elementor", "PHP", "JQuery", "Bootstrap"],
    url: "#",
    year: "2024",
    thumb: "https://iili.io/JaPi3HQ.png",
  },
  {
    title: "FiniteArt",
    titlesub: "arts meet crypto, art store",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Website development to deployment",
      "Product web service connected to 3rd party cms",
      "Integrate email and whatsApp",
      "Payment integration with custom addons",
    ],
    type: ["Website", "Ecommerce"],
    tech: [
      "Wordpress",
      "Elementor",
      "Gravity Form",
      "PHP",
      "JQuery",
      "Artgalleria",
      "WhatsApp",
    ],
    url: "https://finiteart.com.au/",
    year: "2023",
    thumb: "https://iili.io/JaPifDP.png",
  },
  {
    title: "Orientfreight",
    titlesub: "logistics site",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Form entry submission integrated on zoho cms and auto invoice",
      "Forms integrated to google services",
      "Custom order form developments",
      "Order/Package tracking integrated with google sheets",
    ],
    type: ["Website", "Logistic", "CMS"],
    tech: [
      "Wordpress",
      "Elementor",
      "Gravity Form",
      "PHP",
      "JQuery",
      "Google Sheets",
      "Zoho cms and Books",
    ],
    url: "https://orientfreight.com.au/",
    year: "2023",
    thumb: "https://iili.io/JaPiBx1.png",
  },
  {
    title: "Manifest Prizes",
    titlesub: "live Competitions",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Website development to deployment",
      "Plugin development for reward lounge, addhook on woo plugin custom notification",
      "Cronjob implementation for the generated password time limitation on every product purchased",
    ],
    type: ["Website", "Competitions"],
    tech: ["Wordpress", "Elementor", "Gravity Form", "PHP", "JQuery"],
    url: "https://manifestprizes.com.au/",
    year: "2023",
    thumb: "https://iili.io/JaPiKOB.png",
  },
  {
    title: "Motortrade",
    titlesub: "motorcycle dealer website",
    img: "",
    details: [
      "Frontend integration using jquery and php",
      "Custom filters and search for products",
      "Custom plugin development for Loan calculator and product display",
      "Integration with google forms and analytics",
      "Website maintenance, products updates",
    ],
    type: ["Website", "Motorcycle store"],
    tech: ["Wordpress", "Elementor", "PHP", "JQuery", "Google Forms"],
    url: "https://motortrade.com.ph/",
    year: "2023",
    thumb: "https://iili.io/JaPiCWF.png",
  },
  {
    title: "EstimateOz",
    titlesub: "Commercial and residential projects landing page",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Swipepage", "Mailchimp"],
    url: "https://www.estimateoz.com/",
    year: "2023",
    thumb: "../assets/mani.png",
  },
  {
    title: "Learn in Au",
    titlesub: "Course | Chef Commercial Cooking landing page",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Swipepage", "Mailchimp"],
    url: "https://www.learninau.com/",
    year: "2023",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "Neptune Homes",
    titlesub: "design, plans and build homes",
    img: "",
    details: [
      "Responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin for filter and search",
    ],
    type: ["Website", "Reservations"],
    tech: ["Wordpress", "Elementor", "PHP", "JQuery"],
    url: "https://neptunehomes.com.au/",
    year: "2022",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "Fidarzi",
    titlesub: "affiliate website",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Integration of form entries to affiliates",
      "Metamask integrations",
      "Google analytics",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Elementor", "Gravity Form", "PHP", "JQuery"],
    url: "https://fidarzi.com/",
    year: "2022",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "ParadiseResort",
    titlesub: "australia's best family resort",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Beaver Builder", "Gravity Form", "PHP", "JQuery"],
    url: "https://paradiseresort.com.au/",
    year: "2022",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "Sleepsophie",
    titlesub: "australia's smartest sleep company",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Elementor", "PHP", "JQuery"],
    url: "https://sleepsophie.com.au/",
    year: "2022",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "VPC",
    titlesub:
      "charity providing information, representation and a collective voice to those supporting children",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Elementor", "PHP", "JQuery"],
    url: "https://vicparentscouncil.vic.edu.au/",
    year: "2021",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "Kristenlonie",
    titlesub: "bikini shop website",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Elementor", "PHP", "JQuery"],
    url: "https://kristenlonie.com/",
    year: "2021",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "DesignRV",
    titlesub: "Australian Caravanners with a quality website",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Elementor", "PHP", "JQuery"],
    url: "https://designrv.com.au/",
    year: "2021",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "Debrapascoe",
    titlesub: "personal website",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Elementor", "PHP", "JQuery"],
    url: "https://debrapascoe.com/",
    year: "2021",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "O ano G",
    titlesub: "game show website",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Elementor", "PHP", "JQuery"],
    url: "https://oanog.com/",
    year: "2021",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "Prime Exposure",
    titlesub: "professional concreting product website",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Elementor", "PHP", "JQuery"],
    url: "http://primexposure.com.au/",
    year: "2021",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "Little Green Truck",
    titlesub: "delivery service website",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Elementor", "PHP", "JQuery"],
    url: "https://littlegreentruck.com.au/",
    year: "2021",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "BAA",
    titlesub: "branding and driving result",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Elementor", "PHP", "JQuery"],
    url: "https://brandactivation.agency/",
    year: "2021",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "ImpactDesign",
    titlesub: "home builders website",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Elementor", "PHP", "JQuery"],
    url: "https://www.impactdesign.net/",
    year: "2020",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "IDN-REFRESH",
    titlesub: "generic core api platform, designed to support subscription",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
      "Lead Developer and Project Scrum master",
    ],
    type: ["CMS App"],
    tech: ["AngularJs", "Ionic", "Bootstrap", "Material UI"],
    url: "",
    year: "2020",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "GLOBAL EXPERIENCE LANGUAGE(GEL)",
    titlesub: "UI component library",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["UI Library"],
    tech: ["AngularJs", "Ionic", "Bootstrap", "Material UI"],
    url: "",
    year: "2020",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "ENGAGIS CREATIVES",
    titlesub: "UI component library",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Divi", "Bootstrap", "JQuery"],
    url: "",
    year: "2019",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "INFINITY TRAVEL",
    titlesub: "UI component library",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website"],
    tech: ["Wordpress", "Divi", "Bootstrap", "JQuery"],
    url: "",
    year: "2019",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "COMFEE and DENTLUX",
    titlesub: "website design",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Website Design"],
    tech: ["Wordpress", "Divi", "Bootstrap", "JQuery"],
    url: "",
    year: "2019",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "SM, Subaru and Toyota",
    titlesub: "mobile app prototyping",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Mobile App"],
    tech: ["Ionic", "MaterialUI", "Bootstrap", "JQuery"],
    url: "",
    year: "2019",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "Printable Mockup",
    titlesub: "mockup design",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Mockup"],
    tech: ["Wordpress", "Divi", "Bootstrap", "JQuery"],
    url: "",
    year: "2018",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "CUA’s",
    titlesub: "digital brochure financial and insurance products",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Kiosk App"],
    tech: ["Ionic", "AngularJS", "Bootstrap", "JQuery"],
    url: "",
    year: "2018",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "Bunnings",
    titlesub:
      "store kiosk apps that help consumers with easy step-by-step instructions",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Kiosk App"],
    tech: ["AngularJS", "Bootstrap", "JQuery"],
    url: "",
    year: "2018",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "Tessa",
    titlesub: "cms platform design to handle all company project api",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["CMS"],
    tech: ["AngularJS", "Bootstrap"],
    url: "",
    year: "2017",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "Symphony",
    titlesub: "cms platform design to handle all company project api",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["CMS"],
    tech: ["AngularJS", "Bootstrap"],
    url: "",
    year: "2016",
    thumb: "/src/assets/mani.png",
  },
  {
    title: "Worker App",
    titlesub: "design to allocate work time online using mobile",
    img: "",
    details: [
      "Design implementation, responsive display",
      "Frontend integration using jquery and php",
      "Backend integration using php sql",
      "Custom plugin and theme development",
    ],
    type: ["Mobile App"],
    tech: ["AngularJS", "Bootstrap", "Ionic"],
    url: "",
    year: "2016",
    thumb: "/src/assets/mani.png",
  },
];

export const otherproj = [
  {
    year: "2024",
    title: "Local store Inventory and Sales management using google sheet",
    thumb: "/src/assets/mani.png",
  },
];
